name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Caching helps speed up builds
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build
        working-directory: ./client
        run: npm run build

      - name: Fix GitHub Pages routing and assets
        working-directory: ./client
        run: |
          cp dist/index.html dist/404.html
          touch dist/.nojekyll

      # STEP: Add your specific deployment action below.
      # Example: If deploying a static site to GitHub Pages:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist